In [1]:
import numpy as np
%matplotlib notebook

# Matrix Review

Take the matricies:

$\bf{A} =
\begin{pmatrix}
2 & 4 & -7\\
3 & -3 & 0\\
1 & 7 & 5
\end{pmatrix},\;\;
\bf{B} =
\begin{pmatrix}
2 & 4\\
3 & -3\\
1 & 7
\end{pmatrix}, \;\;
\bf{C} =
\begin{pmatrix}
-1 & 1\\
1 & -1
\end{pmatrix}, \;\;
\bf{D} = 
\begin{pmatrix}
2 & 0\\
-3 & 6
\end{pmatrix}
$ 

Define the matricies as numpy arrays

In [4]:
A = np.array([[2,4,-7],
             [3,-3,0],
             [1,7,5]])
B = np.array([[2,4],
             [3,-3],
             [1,7]])
C = np.array([[-1,1],
             [1,-1]])
D = np.array([[2,0],
             [-3,6]])
print(A)
print(B)
print(C)
print(D)

[[ 2  4 -7]
 [ 3 -3  0]
 [ 1  7  5]]
[[ 2  4]
 [ 3 -3]
 [ 1  7]]
[[-1  1]
 [ 1 -1]]
[[ 2  0]
 [-3  6]]


1. Multiply $\bf{A}$ by 2.5 

In [6]:
print(A*2.5)

[[  5.   10.  -17.5]
 [  7.5  -7.5   0. ]
 [  2.5  17.5  12.5]]


2. Evaluate the product of $\bf{C}\cdot\bf{A}$ 

Did you get an error? Do you know why? (Hint: look at the dimensions of the matrix)
- Got an error. the matrices are 2x2 and 3x3, so can't multiply need number of rows to match columns of other 

In [8]:
CA = np.matmul(C,A)
print(CA)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 2)

3. Evaluate the product of $\bf{C}\cdot\bf{D}$ and then $\bf{D}\cdot\bf{C}$. Do you get the same results? 
- different answers CD != DC

In [12]:
CD = np.matmul(C,D)
DC = np.matmul(D,C)
print(CD)
print(DC)

[[-5  6]
 [ 5 -6]]
[[-2  2]
 [ 9 -9]]


4. Find the transpose of $\bf{B}$

In [14]:
B_T = B.T
print(B_T)

[[ 2  3  1]
 [ 4 -3  7]]


5. Add $\bf{C} + \bf{D}$

In [16]:
CD_add = C+D
print(CD_add)

[[ 1  1]
 [-2  5]]


6. Compute the determinate of $\bf{C}$

In [18]:
detC = np.linalg.det(C)
print(detC)

0.0


7. Compute the determinate of $\bf{A}$

In [20]:
detA = np.linalg.det(A)
print(detA)

-257.9999999999998
